# Generated by Django 4.2.7 on 2025-11-09 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency_level',
        ),
    ]
