# Generated by Django 4.2.7 on 2025-11-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_skill_proficiency_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Creative, Winner, Smart, Powerful', max_length=100)),
                ('icon', models.CharField(help_text='Icon class name, emoji, or icon identifier', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Attribute',
                'verbose_name_plural': 'Skill Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_won', models.IntegerField(default=0)),
                ('happy_customers', models.IntegerField(default=0)),
                ('projects_done', models.IntegerField(default=0)),
                ('games_played', models.CharField(blank=True, help_text="e.g., '4000hrs' or '4000 hrs'", max_length=50, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=200)),
                ('author_title', models.CharField(blank=True, max_length=200, null=True)),
                ('author_company', models.CharField(blank=True, max_length=200, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='about',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='home_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload PDF or DOCX resume', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='about',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
