# Generated by Django 4.2.7 on 2025-11-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skillattribute_statistics_testimonial_about_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='hero_button_link',
            field=models.CharField(blank=True, default='#about', help_text="Link URL for the hero action button (e.g., '#about', '/contact', 'https://...')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_button_text',
            field=models.CharField(blank=True, default='Learn More', help_text='Text for the hero action button', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='show_hero_button',
            field=models.BooleanField(default=True, help_text='Show/hide the hero action button'),
        ),
        migrations.AddField(
            model_name='about',
            name='tagline',
            field=models.CharField(blank=True, help_text="Hero section tagline (e.g., 'Developer • Traveler • Freelancer')", max_length=200, null=True),
        ),
    ]
