# Generated by Django 4.2.7 on 2025-11-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_about_hero_button_link_about_hero_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Menu item label (e.g., 'Home', 'About', 'Contact')", max_length=100)),
                ('link', models.CharField(help_text="Link URL (e.g., '#home', '#about', '/contact')", max_length=200)),
                ('is_cta', models.BooleanField(default=False, help_text='Mark as Call-to-Action button (styled differently)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(blank=True, default='Basic Info About Me', max_length=200, null=True)),
                ('skills_title', models.CharField(blank=True, default='Skills', max_length=200, null=True)),
                ('experience_title', models.CharField(blank=True, default='Experience', max_length=200, null=True)),
                ('projects_title', models.CharField(blank=True, default='Projects', max_length=200, null=True)),
                ('education_title', models.CharField(blank=True, default='Education', max_length=200, null=True)),
                ('awards_title', models.CharField(blank=True, default='Awards', max_length=200, null=True)),
                ('hobbies_title', models.CharField(blank=True, default='Hobbies', max_length=200, null=True)),
                ('contact_title', models.CharField(blank=True, default='Contact', max_length=200, null=True)),
                ('testimonials_title', models.CharField(blank=True, default='Testimonials', max_length=200, null=True)),
                ('footer_text', models.CharField(blank=True, default='All rights reserved.', max_length=500, null=True)),
                ('copyright_year', models.IntegerField(blank=True, help_text='Leave empty to use current year', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='about',
            name='image_shape',
            field=models.CharField(choices=[('rounded', 'Rounded'), ('square', 'Square'), ('circle', 'Circle'), ('diamond', 'Diamond')], default='rounded', help_text='Shape style for profile image', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='image_shape',
            field=models.CharField(choices=[('rounded', 'Rounded'), ('square', 'Square'), ('circle', 'Circle'), ('diamond', 'Diamond')], default='rounded', help_text='Shape style for project image', max_length=20),
        ),
    ]
