# Generated by Django 4.2.7 on 2025-11-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_navigationitem_sitesettings_about_image_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='show_about_image',
            field=models.BooleanField(default=True, help_text='Show/hide profile image in About section'),
        ),
    ]
